openapi: 3.0.0
servers:
  - description: Development
    url: 'https://example.io/'
info:
  description: This is a simple API
  version: "1.0.0"
  title: Example
  contact:
    email: huucuong1612@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  
paths: null   
